### ISSUE TITLE
Allow specialops to be enabled per chain

### ISSUE THREAD

**Issue by christopheradams** [proofofexistence/proofofexistence#35]
Not all chains will support specialops out of the gate.

The services config can either be `specialops: '/opcodes'` or `specialops: true`.

**Comment by rejon** [comment]
Can we do this and get this version 2 out?

**Comment by rejon** [comment]
Strange, I cannot assign or do anthing here. @clemsos can you give me permission

**Comment by christopheradams** [comment]
We can skip this. If the insight server does not support opcodes, it will 404 and the user will just see the "No transactions available" message. From the user's perspective nothing is broken.
