### ISSUE TITLE
Hashing fails on larger files

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#43]
Appeared on Chrome with file of size > 200Mo

**Comment by rejon** [comment]
Ok, so someone can do this from commandline or enter hash. Can we add a file check in here for anything over 200 MB and give alert from user interface side?

**Comment by clemsos** [comment]
This is how it looks like

<img width="758" alt="screen shot 2018-06-13 at 10 30 59" src="https://user-images.githubusercontent.com/743246/41339359-e750f1b0-6ef4-11e8-8ddb-8726c827627e.png">

@christopheradams @rejon any idea for better language maybe?

**Comment by rejon** [comment]
SUPER UGLY

**Comment by clemsos** [comment]
@rejon Hahaha yes true
