### ISSUE TITLE
Clearer way to prove existing documents

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#48]
Several persons are asking how to find hash without using the website.    
Need a button or sth

> I used your service, and I was wondering in case your website does not work anymore, how can I demonstrate that my document corresponds to the hash in the blockchain?
> In other words, how can I find the hash of my document, if I do not use your website?

Should be very explicit about how this hash is generated and how user can reproduce on their own machine.

**Comment by rejon** [comment]
SINCE we are not running two service, we can encourage others to use this codebase to make sites to test against...

**Comment by christopheradams** [comment]
> how can I find the hash of my document, if I do not use your website?

The docs explain how to use `shasum` or JS to calculate the hash of any document: https://docs.proofofexistence.com/#/api?id=calculating-the-sha256-digest
