### ISSUE TITLE
Safely store db on Docker deployment

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#50]
To make sure the database is not erased at restart, we need to use `docker-compose.yml` file and add a [VOLUME](https://docs.docker.com/engine/reference/builder/#volume) command in the Dockerfile that will create a mount point to the host rep.

**Comment by rejon** [comment]
Yeah, this is good.

**Comment by qinfengling** [comment]
For local usage, we can override the configuration with environment, 
https://docs.proofofexistence.com/#/deployment?id=startstop-the-image

For AWS ECS, we can use ecs task like this:
https://docs.proofofexistence.com/#/deployment?id=deployment-with-amazon-elastic-container-service

**Comment by qinfengling** [comment]
Fixed.
