### ISSUE TITLE
Implement dynamic pricing

### ISSUE THREAD

**Issue by christopheradams** [proofofexistence/proofofexistence#52]
We should have enough information to calculate the docproof price dynamically, rather than having a price set the the config that has to be updated manually.

However, the dynamic price should have the following goals:

1. As low as possible but above the median mining fee.
2. Retain ability to configure a fee multiplier, so that the target mining fee can deviate from the median fee in a regular way, in order to change mining priority.
3. The price should not appear arbitrary. Always round up to the nearest 0.5 mBTC.
4. The price should not change frequently. Cache the price and expire the cache once per day.

**Comment by rejon** [comment]
Agree a 24 hour average.

**Comment by rejon** [comment]
Is #40 a duplicate?
