### ISSUE TITLE
How do you get the xprv key for a Bitcoin Cash wallet?

### ISSUE THREAD

**Issue by elliot-sawyer** [proofofexistence/proofofexistence#62]
I'm using the BCH testnet (with Electron Cash client) and it's not clear how to obtain an xprv key from it. Is there an alternative format that I can use, or configure POEX to use a single pub/priv key instead of an HD wallet? I'm getting the following error on `npm start`
```
throw HDPrivateKey.getSerializedError(arg);
^
Invalid length for xprivkey string in <truncated>
```

**Comment by christopheradams** [comment]
The software only supports HD wallets.

What format is your BCH testnet wallet in? This might be a better question for https://github.com/bitpay/bitcore-lib-cash or Electron Cash.

**Comment by elliot-sawyer** [comment]
UPDATE: If anybody else is looking for an xprv and xpub from Electron Cash, there's one very ill-advised method you can use to get it. Please don't do this unless you're desperate, and I'm certainly not going to do it for a mainnet wallet!

The keys don't seem to be exposed by the GUI or the console anywhere so I had to resort to some manual work. You can get both keys by removing the passphrase on wallet.dat (so that it's permanently decrypted) and opening the file in a hex editor. Just grep/search for "xprv". You should re-encrypt it with a passphrase when you're finished to prevent wallet theft. 

You can also use the CoPay wallet, which exposes the tpub/xpub and tprv/xprv through the wallet if you need it.
