### ISSUE TITLE
App should return 404 status

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#67]
Currently hitting a non-existing page will return status 200 because `index.html` is served anyway. There is  a proper 404 error page showing but the status code returned is wrong.

Then maybe we don't need to fix that 

> In a SPA (Single Page Application), there isn't network traffic but just switching of panes. The HTTP error code is in the headers for serving a new page, while all the content is in a named <div> that doesn't reload a new page. One would need to toss out page, transmit and render a new page to have the 404 return code, and then send the original page again when the user moves away.
>
> And, its only the user. The 404 error code, or any other HTTP code, is really a hint to the browser or service. If the requester is a browser, the human is given a better indication than the browser could provide. If the requestor is a crawler, it probably scans for 404 in h1's. If the requester is using your website as an API, why is that a good thing?

from https://stackoverflow.com/a/43019110/887594

@qinfengling

**Comment by qinfengling** [comment]
Thanks. make sense.

Keep it as a won't fix issue.
