### ISSUE TITLE
There was an error connecting to our payment API. Please try again later.

### ISSUE THREAD

**Issue by SystemChanger** [proofofexistence/proofofexistence#68]
Hi!
I can't continue certification due to the error "There was an error connecting to our payment API. Please try again later.".
Is the service still alive?

https://proofofexistence.com/detail/0b716a5f1e11b7afd8bb142b9a0806c43363baf164b8c4ee6df18b5075d8025d

**Comment by qinfengling** [comment]
@SystemChanger Thanks for your report.
The service is still alive right now.
We have fixed the error that found in our payment API.
Please go-ahead to the next step. your payment will never be lost.

**Comment by SystemChanger** [comment]
It works right now, ty.
