### ISSUE TITLE
How to see a time-stamped document

### ISSUE THREAD

**Issue by DLemon-max** [proofofexistence/proofofexistence#71]
Few years ago I time-stamped few documents using proofofexistence site.

Now I need to see the documents. Where can I see it ?

p.s.
I did find the time-stamp it self, but couldnt find the docs that were time stamped.

Thanks,

D

**Comment by clemsos** [comment]
Hi, we can not help you finding the documents as we don’t store any file - only the computed hash in the BTC blockchain. We don’t even send files to our servers, all process is done by the client.

**Comment by DLemon-max** [comment]
So how can I correlate the computed hash to the document I time-stamped ?

**Comment by clemsos** [comment]
You need to compute the SHA256 checksum / hash from the original document. If the document is exactly identical to the one uploaded, the computed hash will be identical.

**Comment by DLemon-max** [comment]
Can you please give me instructions how to do it ?

**Comment by clemsos** [comment]
> Can you please give me instructions how to do it ?

If you reupload the exact same file to proofofexistence.com, you should be prompted with the tx where the hash has already been written.

Alternatively you can use command line tools (see [here](https://help.rublon.com/en/support/solutions/articles/1000308518-how-to-verify-sha-256-checksum-)) or use an online service - google "SHA256 Checksum file".

Hope that helps !

**Comment by DLemon-max** [comment]
Does it mean that I need to pay again for each reupload ?

**Comment by clemsos** [comment]
No, if the document has already been uploaded, you should be redirected to a page showing the transaction hash

**Comment by DLemon-max** [comment]
Thanks much Clement. You have been very helpful.
