### ISSUE TITLE
Wrong timestamp in Certified documents

### ISSUE THREAD

**Issue by clemsos** [proofofexistence/proofofexistence#9]
Also visible on the home page

<img width="655" alt="screen shot 2018-04-09 at 21 55 38" src="https://user-images.githubusercontent.com/743246/38519661-dfd1d9ea-3c40-11e8-8824-0330f632f29b.png">

**Comment by christopheradams** [comment]
Fixed in e100cee8291e743cc0b9a36ccac26ad081f94240. Existing records however cannot be updated (no migrations).
